-- TABLE ROW COUNTS

SELECT 'CUSTOMERS' AS TABLE_NAME, COUNT(*) AS RECORDS
FROM CUSTOMERS
UNION ALL
SELECT 'ORDERS', count(*)
FROM ORDERS
UNION ALL
SELECT 'ORDER_ITEMS', COUNT(*)
FROM ORDER_ITEMS
UNION ALL
SELECT 'PRODUCTS', COUNT(*)
FROM PRODUCTS
UNION ALL
SELECT 'INVENTORY', COUNT(*)
FROM INVENTORY
UNION ALL
SELECT 'CUSTOMER_FEEBACK', COUNT(*)
FROM CUSTOMER_FEEDBACK
UNION ALL
SELECT 'DELIVERY_PERFORMANCE', COUNT(*)
FROM DELIVERY_PERFORMANCE
UNION ALL
SELECT 'MARKETING_PERFORMANCE', COUNT(*)
FROM MARKETING_PERFORMANCE
ORDER BY TABLE_NAME ASC;

-- DATA COVERAGE ANALYSIS

-- 1. ORDERS
SELECT MIN(ORDER_DATE) AS FIRST_ORDER, MAX(ORDER_DATE) AS LAST_ORDER
FROM ORDERS;

-- 2. FEEDBACK
SELECT MIN(FEEDBACK_DATE), MAX(FEEDBACK_DATE)
FROM CUSTOMER_FEEDBACK;

-- 3. MARKETING
SELECT MIN(DATE), MAX(DATE)
FROM MARKETING_PERFORMANCE;

-- CUSTOMER OVERVIEW

-- 1. TOTAL CUSTOMERS
SELECT COUNT(*) AS TOTAL_CUSTOMERS
FROM CUSTOMERS;

-- 2. CUSTOMER SEGMENTS
SELECT customer_segment, COUNT(*) AS CUSTOMERS
FROM CUSTOMERS
GROUP BY customer_segment
ORDER BY CUSTOMERS DESC;

-- 3. REGISTRATION TREND
SELECT YEAR(REGISTRATION_DATE) AS YEAR, monthname(REGISTRATION_DATE) AS MONTH, COUNT(*) AS NEW_CUSTOMERS
FROM CUSTOMERS
GROUP BY YEAR(REGISTRATION_DATE), MONTHNAME(REGISTRATION_DATE)
ORDER BY YEAR, MONTH;

-- ORDER OVERVIEW

-- 1. TOTAL ORDERS
SELECT count(*) AS TOTAL_ORDERS
FROM ORDERS;

-- 2. REVENUE
SELECT ROUND(SUM(ORDER_TOTAL), 2) AS TOTAL_REVENUE
FROM ORDERS;

-- 3. AVERAGE ORDER VALUE
SELECT ROUND(AVG(ORDER_TOTAL), 2) AS AVG_ORDER_VALUE
FROM ORDERS;

-- 4. MAXIMUM & MINIMUM ORDER VALUE
SELECT MAX(ORDER_TOTAL) AS MAX_ORDER_VALUE, MIN(ORDER_TOTAL) AS MIN_ORDER_VALUE
FROM ORDERS;

-- 5. PAYMENT METHODS
SELECT PAYMENT_METHOD, COUNT(*) AS ORDERS
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY ORDERS DESC;

-- PRODUCT OVERVIEW

-- 1. TOTAL PRODUCTS
SELECT COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS;

-- 2. PRODUCTS BY CATEGORY
SELECT CATEGORY, COUNT(*) AS PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY PRODUCTS DESC;

-- 3. PRODUCTS BY BRAND
SELECT BRAND, COUNT(*) AS PRODUCTS
FROM PRODUCTS
GROUP BY BRAND
ORDER BY PRODUCTS DESC
LIMIT 5;

-- 4. PRICE STATISTICS
SELECT MAX(PRICE), MIN(PRICE), ROUND(AVG(PRICE), 2)
FROM PRODUCTS;

-- DELIVERY OVERVIEW

-- 1. DELIVERY STATUS
SELECT DELIVERY_STATUS, COUNT(*) AS ORDERS
FROM DELIVERY_PERFORMANCE
GROUP BY DELIVERY_STATUS
ORDER BY ORDERS DESC;

-- 2. AVERAGE DELIVERY TIME
SELECT AVG(DELIVERY_TIME_MINUTES) AS AVG_DELIVERY_TIME_MINUTES
FROM DELIVERY_PERFORMANCE;

-- 3. DELAY REASONS
SELECT REASONS_IF_DELAYED, COUNT(*) AS OCCURANCE
FROM DELIVERY_PERFORMANCE
WHERE REASONS_IF_DELAYED != "" AND REASONS_IF_DELAYED IS NOT NULL
GROUP BY REASONS_IF_DELAYED
ORDER BY OCCURANCE DESC;

-- INVENTORY OVERVIEW

-- 1. INVENTORY RECORDS
SELECT COUNT(*) AS RECORDS
FROM INVENTORY;

-- 2. DAMAGED STOCKS
SELECT ROUND(SUM(DAMAGED_STOCK), 2) AS TOTAL_DAMAGED_STOCKS
FROM INVENTORY;

-- 3. STOCK RECIEVED
SELECT ROUND(SUM(STOCK_RECEIVED), 2) AS TOTAL_STOCK_RECEIVED
FROM INVENTORY;

-- CUSTOMER FEEDBACK OVERVIEW

-- 1. RATING DISTRIBUTION
SELECT RATING, COUNT(*) AS REVIEWS
FROM CUSTOMER_FEEDBACK
GROUP BY RATING
ORDER BY REVIEWS DESC;

-- 2. SENTIMENT ANALYSIS
SELECT SENTIMENT, COUNT(*) AS REVIEWS
FROM CUSTOMER_FEEDBACK
GROUP BY SENTIMENT
ORDER BY REVIEWS DESC;

-- 3. FEEDBACK CATEGORIES
SELECT FEEDBACK_CATEGORY, COUNT(*) AS REVIEWS
FROM CUSTOMER_FEEDBACK
GROUP BY FEEDBACK_CATEGORY
ORDER BY REVIEWS DESC;

-- MARKETING OVERVIEW

-- 1. CAMPAIGN PERFORMANCE
SELECT CAMPAIGN_NAME, SUM(IMPRESSIONS) AS IMPRESSIONS, 
SUM(CLICKS) AS CLICKS, SUM(CONVERSIONS) AS CONVERSIONS
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY CONVERSIONS DESC;

-- 2. OVERALL CONVERSION RATE
SELECT ROUND(SUM(CONVERSIONS)*100.0/SUM(CLICKS), 2) AS CONVERSION_RATE
FROM MARKETING_PERFORMANCE;

-- 3. ROAS
SELECT ROUND(SUM(REVENUE_GENERATED)/SUM(SPEND), 2) AS OVERALL_ROAS
FROM MARKETING_PERFORMANCE;