-- 1. CHECKING FOR NULL VALUES

SELECT * FROM CUSTOMERS
WHERE customer_id IS NULL
 OR customer_name IS NULL
 OR email IS NULL
 OR phone IS NULL
 OR address IS NULL
 OR area IS NULL
 OR pincode IS NULL
 OR registration_date IS NULL
 OR customer_segment IS NULL
 OR total_orders IS NULL
 OR avg_order_value IS NULL;

-- THERE IS NO NULL VALUES IN CUSTOMERS DATA.

SELECT * FROM CUSTOMER_FEEDBACK
WHERE feedback_id IS NULL
OR order_id IS NULL
OR customer_id IS NULL
OR rating IS NULL
OR feedback_text IS NULL
OR feedback_category IS NULL
OR sentiment IS NULL
OR feedback_date IS NULL;

-- THERE IS NO NULL VALUES IN CUSTOMER_FEEDBACK DATA.

SELECT * FROM DELIVERY_PERFORMANCE
WHERE order_id IS NULL
OR delivery_partner_id IS NULL
OR promised_time IS NULL
OR actual_time IS NULL
OR delivery_time_minutes IS NULL
OR distance_km IS NULL
OR delivery_status IS NULL
OR reasons_if_delayed IS NULL;

-- THERE IS NO NULL VALUE IN DELIVERY_PERFORMANCE.

SELECT * FROM INVENTORY
WHERE product_id IS NULL
OR date IS NULL
OR stock_received IS NULL
OR damaged_stock IS NULL;

-- THERE IS NO NULL VALUES IN INVENTORY DATA

SELECT * FROM MARKETING_PERFORMANCE
WHERE campaign_id IS NULL
OR campaign_name IS NULL
OR date IS NULL
OR target_audience IS NULL
OR channel IS NULL
OR impressions IS NULL
OR clicks IS NULL
OR conversions IS NULL
OR spend IS NULL
OR revenue_generated IS NULL
OR roas IS NULL;

-- THERE IS NO NULL VALUES IN MARKETING PERFORMANCE DATA.


SELECT * FROM ORDER_ITEMS
WHERE order_id IS NULL
OR product_id IS NULL
OR quantity IS NULL
OR unit_price IS NULL;

-- THERE IS NO NULL VALUES IN ORDER_ITEMS DATA.

SELECT * FROM ORDERS
WHERE order_id IS NULL
OR customer_id IS NULL
OR order_date IS NULL
OR promised_delivery_time IS NULL
OR actual_delivery_time IS NULL
OR delivery_status IS NULL
OR order_total IS NULL
OR payment_method IS NULL
OR delivery_partner_id IS NULL
OR store_id IS NULL;

-- THERE IS NO NULL VALUES IN ORDERS DATA.

SELECT * FROM PRODUCTS
WHERE product_id IS NULL
OR product_name IS NULL
OR category IS NULL
OR brand IS NULL
OR price IS NULL
OR mrp IS NULL
OR margin_percentage IS NULL
OR shelf_life_days IS NULL
OR min_stock_level IS NULL
OR max_stock_level IS NULL;

-- THERE IS NO NULL VALUES IN PRODUCTS DATA.

-- 2. CHECKING FOR DUPLICATE VALUES

SELECT (COUNT(*) - COUNT(DISTINCT CUSTOMER_ID)) AS DUPLICATE_VALUES FROM CUSTOMERS;

-- THERE IS NO DUPLICATE VALUES IN CUSTOMERS DATA.

SELECT (COUNT(*) - COUNT(DISTINCT FEEDBACK_ID)) AS DUPLICATE_VALUES FROM CUSTOMER_FEEDBACK;

-- THERE IS NO DUPLICATE VALUES IN CUSTOMER_FEEDBACK DATA.

SELECT (COUNT(*) - COUNT(DISTINCT ORDER_ID)) AS DUPLICATE_VALUES FROM DELIVERY_PERFORMANCE;

-- THERE IS NO DUPLICATE VALUES IN DELIVERY_PERFORMANCE DATA.

SELECT (COUNT(*) - COUNT(DISTINCT CAMPAIGN_ID)) AS DUPLICATE_VALUES FROM MARKETING_PERFORMANCE;

-- THERE IS NO DUPLICATE VALUES IN MARKETING_PERFORMANCE DATA.

SELECT (COUNT(*) - COUNT(DISTINCT ORDER_ID)) AS DUPLICATE_VALUES FROM ORDER_ITEMS;

-- THERE IS NO DUPLICATE IN ORDER_ITEMS DATA.

SELECT (COUNT(*) - COUNT(DISTINCT ORDER_ID)) AS DUPLICATE_VALUES FROM ORDERS;

-- THERE IS NO DUPLICATE VALUES IN ORDERS DATA.

SELECT (COUNT(*) - COUNT(DISTINCT PRODUCT_ID)) AS DUPLICATE_VALUES FROM PRODUCTS;

-- THERE IS NO DUPLICATE VALUES IN PRODUCTS DATA.

-- 3. CHECKING FOR NEGATIVE SALES

SELECT * 
FROM ORDERS
WHERE ORDER_TOTAL < 0;

-- THERE IS NO NEGATIVE SALE IN THE DATA.
