-- NULL VALUE ANALYSIS

-- 1. CUSTOMERS
SELECT COUNT(*) AS NULL_CUSTOMER_ID
FROM customers
WHERE customer_id IS NULL;

SELECT COUNT(*) AS NULL_CUSTOMER_NAME
FROM customers
WHERE CUSTOMER_NAME IS NULL;

SELECT COUNT(*) AS NULL_REGISTRATION_DATE
FROM customers
WHERE REGISTRATION_DATE IS NULL;

-- 2. ORDERS
SELECT COUNT(*) AS NULL_ORDER_ID
FROM ORDERS
WHERE ORDER_ID IS NULL;

SELECT COUNT(*) AS NULL_CUSTOMER_ID
FROM ORDERS
WHERE CUSTOMER_ID IS NULL;

SELECT COUNT(*) AS NULL_ORDER_TOTAL
FROM ORDERS
WHERE ORDER_TOTAL IS NULL;

SELECT COUNT(*) AS NULL_ORDER_DATE
FROM ORDERS
WHERE ORDER_DATE IS NULL;

-- 3. PRODUCTS
SELECT COUNT(*) AS NULL_PRODUCT_ID
FROM products
WHERE product_id IS NULL;

SELECT COUNT(*) AS NULL_CATEGORY
FROM products
WHERE CATEGORY IS NULL;

SELECT COUNT(*) AS NULL_PRICE
FROM products
WHERE PRICE IS NULL;

-- DUPLICATE ANALYSIS

-- 1. ORDERS
SELECT ORDER_ID, COUNT(*) AS OCCURANCE
FROM ORDERS
GROUP BY ORDER_ID
HAVING count(*) > 1;

-- 2. CUSTOMERS
SELECT CUSTOMER_ID, COUNT(*) AS OCCURANCE
FROM customers
group by customer_id
having OCCURANCE > 1;

-- 3. PRODUCTS
select product_id, COUNT(*) AS OCCURANCE
FROM products
group by product_id
having OCCURANCE > 1;

-- REFERENTIAL INTIGRITY CHECKS

-- 1. ORDER WITHOUT CUSTOMERS
SELECT count(*) AS MISSING_CUSTOMER_REFERENCE
FROM orders O
LEFT JOIN customers C
ON O.customer_id = C.customer_id
WHERE C.customer_id IS NULL;

-- 2. ORDER ITEMS WITHOUT ORDERS
SELECT COUNT(*) AS MISSING_ORDER_REFERENCE
FROM order_items OI
LEFT JOIN orders O
ON O.order_id = OI.order_id
WHERE O.order_id IS NULL;

-- 3. ORDER ITEM WITHOUT PRODUCTS
SELECT count(*) AS MISSING_PRODUCT_REFERENCE
FROM order_items OI
LEFT JOIN products P
ON P.product_id = OI.product_id
WHERE P.product_id IS NULL;

-- 4. FEEDBACK WITHOUT ORDERS
SELECT COUNT(*) AS MISSING_ORDER_REFERENCE
FROM customer_feedback CF
LEFT JOIN orders O
ON CF.order_id = O.order_id
WHERE O.order_id IS NULL;

-- INVALID VALUE CHECKS

-- 1. NEGATIVE REVENUE
SELECT *
FROM ORDERS
WHERE ORDER_TOTAL < 0;

-- 2. NEGATIVE PRODUCT PRICE
select *
FROM products
WHERE PRICE < 0;

-- 3. NEGATIVE QUANTITY
SELECT *
FROM order_items
WHERE quantity < 0;

-- 4. INVALID RATINGS
SELECT * 
FROM customer_feedback
WHERE rating NOT between 1 AND 5;

-- 5. INVALID MARKETING METRICS
SELECT *
FROM marketing_performance
WHERE impressions < clicks;

SELECT *
FROM marketing_performance
WHERE clicks < conversions;

-- BUSINESS RULE VALIDATION

-- 1. ORDER TOTAL VALIDATION
SELECT O.ORDER_ID, O.ORDER_TOTAL, SUM(OI.QUANTITY * OI.UNIT_PRICE) AS CALCULATED_TOTAL
FROM orders O
JOIN order_items OI
ON O.order_id = OI.order_id
group by O.order_id, O.order_total
having abs(O.ORDER_TOTAL - CALCULATED_TOTAL) > 1;

-- 2. INVENTORY DAMAGE CHECK
SELECT AVG(DAMAGED_STOCK) AS AVG_DAMAGE,
MAX(DAMAGED_STOCK) AS MAX_DAMAGE,
MIN(DAMAGED_STOCK) AS MIN_DAMAGE
FROM INVENTORY;

SELECT SUM(stock_received) AS STOCK_RECEIVED,
sum(damaged_stock) AS DAMAGED_STOCK,
ROUND(SUM(DAMAGED_STOCK) *100.0/SUM(STOCK_RECEIVED), 2) AS DAMAGE_PERCENTAGE
FROM inventory