-- CUSTOMER SEGMENTATION ANALYSIS

SELECT CUSTOMER_SEGMENT, COUNT(*) AS TOTAL_CUSTOMER,
ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM CUSTOMERS),2) AS PERCENTAGE
FROM CUSTOMERS
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_CUSTOMER DESC;

-- CUSTOMER LIFETIME VALUE (CLV)

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, COUNT(ORDER_ID) AS TOTAL_ORDERS,
ROUND(SUM(O.ORDER_TOTAL), 2) AS LIFETIME_VALUE
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
ORDER BY LIFETIME_VALUE DESC
LIMIT 10;

-- TOP 10 CUSTOMERS

SELECT C.CUSTOMER_NAME, COUNT(O.ORDER_ID) AS TOTAL_ORDERS,
ROUND(SUM(O.ORDER_TOTAL), 2) AS REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_NAME
ORDER BY REVENUE DESC, TOTAL_ORDERS DESC
LIMIT 10;

-- REPEAT CUSTOMER ANALYSIS

SELECT C.CUSTOMER_ID, C.CUSTOMER_NAME, COUNT(O.ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS O
JOIN CUSTOMERS C
ON C.CUSTOMER_ID = O.CUSTOMER_ID
GROUP BY C.CUSTOMER_ID, C.CUSTOMER_NAME
HAVING TOTAL_ORDERS > 1
ORDER BY TOTAL_ORDERS DESC
LIMIT 10;

-- REPEAT CUSTOMER RATE

SELECT ROUND(
(SELECT COUNT(*)
FROM (SELECT CUSTOMER_ID
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING COUNT(CUSTOMER_ID) > 1) T
) * 100.0
/
(SELECT COUNT(*) FROM CUSTOMERS)
,2) AS REPEAT_CUSTOMER_RATE;

-- AVERAGE ORDER PER CUSTOMER

SELECT ROUND(
COUNT(ORDER_ID) * 1.0/COUNT(DISTINCT CUSTOMER_ID),
2
) AS AVG_ORDERS_PER_CUSTOMER
FROM ORDERS;

-- CUSTOMER REVENUE DISTRIBUTION

SELECT C.CUSTOMER_SEGMENT, ROUND(SUM(O.ORDER_TOTAL),2) AS REVENUE
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_SEGMENT
ORDER BY REVENUE DESC;

-- NEW VS EXISTING CUSTOMERS

SELECT YEAR(REGISTRATION_DATE) AS YEAR, monthname(REGISTRATION_DATE) AS MONTHS,
COUNT(*) AS TOTAL_CUSTOMERS, SUM(IF(UPPER(CUSTOMER_SEGMENT) = "NEW", 1, 0)) AS NEW_CUSTOMERS 
FROM CUSTOMERS
GROUP BY YEAR(REGISTRATION_DATE), MONTHNAME(REGISTRATION_DATE)
ORDER BY YEAR, MONTHS;