USE BLINKIT;

-- SALES OVERVIEW KPI

-- 1. TOTAL REVENUE
SELECT ROUND(SUM(ORDER_TOTAL), 2) AS TOTAL_REVENUE
FROM ORDERS;

-- 2. TOTAL ORDERS
SELECT COUNT(*) AS TOTAL_ORDERS
FROM ORDERS;

-- 3. AVERAGE ORDER VALUE (AOV)
SELECT ROUND(SUM(ORDER_TOTAL)/COUNT(ORDER_ID), 2) AS AVG_ORDER_VALUE
FROM ORDERS;

-- 4. MAXIMUM AND MINIMUM ORDERS VALUE
SELECT MAX(ORDER_TOTAL) AS MAX_ORDER_VALUE, MIN(ORDER_TOTAL) AS MIN_ORDER_VALUE
FROM ORDERS;

-- MONTHLY REVENUE TREND

SELECT YEAR(ORDER_DATE) AS YEAR, monthname(ORDER_DATE) AS MONTH,
ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE
FROM ORDERS
GROUP BY YEAR(ORDER_DATE), monthname(ORDER_DATE)
order by YEAR, MONTH;

-- MONTHLY ORDER TREND

SELECT YEAR(ORDER_DATE) AS YEAR, monthname(ORDER_DATE) AS MONTH,
COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM ORDERS
GROUP BY year(ORDER_DATE), monthname(ORDER_DATE)
ORDER BY YEAR, MONTH;

-- REVENUE BY PAYMENT METHOD

SELECT PAYMENT_METHOD, COUNT(ORDER_ID) AS ORDERS, ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY REVENUE DESC;

-- REVENUE CONTRIBUTION %

SELECT PAYMENT_METHOD, ROUND(
SUM(ORDER_TOTAL) * 100.0/(SELECT SUM(ORDER_TOTAL) FROM ORDERS)
, 2) AS REVENUE_PERCENTAGE
FROM ORDERS
GROUP BY PAYMENT_METHOD
ORDER BY REVENUE_PERCENTAGE DESC;

-- BEST SALES MONTH

SELECT 
YEAR(ORDER_DATE) AS YEAR,
MONTHNAME(ORDER_DATE) AS MONTH,
ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE
FROM ORDERS
GROUP BY YEAR(ORDER_DATE), monthname(ORDER_DATE)
ORDER BY REVENUE DESC
LIMIT 5;

-- LOWEST SALES MONTH

SELECT 
YEAR(ORDER_DATE) AS YEAR,
MONTHNAME(ORDER_DATE) AS MONTH,
ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE
FROM ORDERS
GROUP BY YEAR(ORDER_DATE), monthname(ORDER_DATE)
ORDER BY REVENUE
LIMIT 5;

-- MONTHLY REVENUE GROWTH %

WITH MONTHLY_REVENUE AS (
	SELECT YEAR(ORDER_DATE) AS YEAR,
    month(ORDER_DATE) AS MONTH,
    ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE
    FROM ORDERS
    group by YEAR(ORDER_DATE), month(ORDER_DATE)
)
SELECT YEAR, MONTH, REVENUE,
LAG(REVENUE) OVER (ORDER BY YEAR, MONTH) AS PREVIOUS_MONTH,
ROUND(
	(
		REVENUE - LAG(REVENUE) OVER (ORDER BY YEAR, MONTH)
	) * 100.0/ LAG(REVENUE) OVER (ORDER BY YEAR, MONTH)
, 2) AS GROWTH_PERCENTAGE
FROM MONTHLY_REVENUE;

-- RUNNING REVENUE (CUMULATIVE REVENUE)

SELECT YEAR(ORDER_DATE) AS YEAR,
MONTH(ORDER_DATE) AS MONTH,
ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE,
ROUND(	SUM(
		SUM(ORDER_TOTAL) ) OVER (ORDER BY YEAR(ORDER_DATE), MONTH(ORDER_DATE)), 2) AS CUMMULATIVE_REVENUE
FROM ORDERS
group by YEAR(ORDER_DATE), MONTH(ORDER_DATE);

-- REVENUE QUARTILE ANALYSIS
WITH QUARTILE_REVENUE AS (
SELECT ntile(4) OVER (ORDER BY ORDER_TOTAL DESC) AS REVENUE_QUARTILE, ORDER_TOTAL
FROM ORDERS)
SELECT REVENUE_QUARTILE, ROUND(SUM(ORDER_TOTAL), 2) AS REVENUE
FROM QUARTILE_REVENUE
GROUP BY REVENUE_QUARTILE;