USE BLINKIT;

-- PRODUCT PORTFOLIO OVERVIEW

-- 1. TOTAL PRODUCTS
SELECT COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS;

-- 2. PRODUCTS BY CATEGORY
SELECT CATEGORY, COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY TOTAL_PRODUCTS DESC;

-- 3. PRODUCTS BY BRAND
SELECT BRAND, COUNT(*) AS TOTAL_PRODUCTS
FROM PRODUCTS
GROUP BY BRAND
ORDER BY TOTAL_PRODUCTS
LIMIT 10;

-- TOP SELLING PRODUCTS

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, SUM(OI.QUANTITY) AS QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
ORDER BY QUANTITY_SOLD DESC
LIMIT 10;

-- HIGHEST REVENUE PRODUCTS

SELECT P.PRODUCT_NAME, ROUND(SUM(OI.QUANTITY * OI.UNIT_PRICE),2) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_NAME
ORDER BY REVENUE DESC
LIMIT 10;

-- CATEGORY REVENUE ANALYSIS

SELECT P.CATEGORY, ROUND(SUM(OI.QUANTITY * OI.UNIT_PRICE),2) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY REVENUE DESC;

-- CATEGORY QUANTITY ANALYSIS

SELECT P.CATEGORY, SUM(OI.QUANTITY) AS QUANTITY_SOLD
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY QUANTITY_SOLD DESC;

-- BRAND PERFORMANCE

SELECT P.BRAND, ROUND(SUM(OI.QUANTITY * OI.UNIT_PRICE), 2) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.BRAND
ORDER BY REVENUE DESC
LIMIT 10;

-- PRODUCT MARGIN ANALYSIS

-- 1. TOP 10 HIGHEST MARGIN PRODUCT
SELECT PRODUCT_NAME, MARGIN_PERCENTAGE, CATEGORY, BRAND
FROM PRODUCTS
ORDER BY MARGIN_PERCENTAGE DESC
LIMIT 10;

-- 2. CATEGORY AVERAGE MARGIN

SELECT CATEGORY, ROUND(AVG(MARGIN_PERCENTAGE),2) AS AVG_MARGIN
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY AVG_MARGIN DESC;

-- INVENTORY RISK ANALYSIS

-- 1. PRODUCTS BELOW MINIMUM STOCK
SELECT
    p.product_id,
    p.product_name,
    p.min_stock_level,
    SUM(i.stock_received) AS total_stock_received,
    SUM(i.damaged_stock) AS total_damaged_stock,
    SUM(i.stock_received - i.damaged_stock) AS net_stock_received
FROM products p
JOIN inventory i
    ON p.product_id = i.product_id
GROUP BY
    p.product_id,
    p.product_name,
    p.min_stock_level
HAVING net_stock_received < p.min_stock_level
ORDER BY net_stock_received;

-- 2. PRODUCTS WITH HIGHEST DAMAGED STOCK
SELECT P.PRODUCT_NAME, SUM(I.DAMAGED_STOCK) AS DAMAGED_STOCKS
FROM PRODUCTS P
JOIN INVENTORY I
ON I.PRODUCT_ID = P.PRODUCT_ID
GROUP BY PRODUCT_NAME
ORDER BY DAMAGED_STOCKS DESC
LIMIT 10;

-- SHELF LIFE ANALYSIS

SELECT CATEGORY, ROUND(AVG(SHELF_LIFE_DAYS), 2) AS AVG_SHELF_LIFE
FROM PRODUCTS
GROUP BY CATEGORY
ORDER BY AVG_SHELF_LIFE DESC;

-- PRODUCT REVENUE CONTRIBUTION %

SELECT P.CATEGORY,
ROUND(SUM(OI.QUANTITY * OI.UNIT_PRICE) * 100.0/ (
SELECT SUM(QUANTITY * UNIT_PRICE)
FROM ORDER_ITEMS
), 2) AS REVENUE_PERCENTAGE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY REVENUE_PERCENTAGE DESC;