USE BLINKIT;

-- INVENTORY OVERVIEW KPIs

-- 1. TOTAL STOCK RECIEVED
SELECT SUM(STOCK_RECEIVED) AS TOTAL_STOCK
FROM inventory;

-- 2. TOTAL DAMAGED STOCK
SELECT SUM(DAMAGED_STOCK) AS TOTAL_DAMAGED_STOCK
FROM inventory;

-- 3. INVENTORY DAMAGE RATE
SELECT ROUND(SUM(DAMAGED_STOCK) * 100.0/ SUM(STOCK_RECEIVED),2) AS DAMAGE_RATE_PERCENTAGE
FROM inventory;

-- MONTHLY INVENTORY TREND

SELECT YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH,
SUM(STOCK_RECEIVED) AS STOCK_RECEIVED
FROM INVENTORY
group by YEAR(DATE), MONTH(DATE)
ORDER BY YEAR, MONTH;

-- MONTHLY DAMAGED STOCK TREND

SELECT YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH,
SUM(DAMAGED_STOCK) AS DAMAGED_STOCK
FROM inventory
GROUP BY year(DATE), month(DATE)
ORDER BY YEAR, month;

-- TOP PRODUCT BY STOCK RECEIVED

SELECT P.PRODUCT_NAME, SUM(I.STOCK_RECEIVED) AS TOTAL_STOCK_RECEIVED
FROM inventory I
JOIN products P
ON P.product_id = I.product_id
group by P.product_name
ORDER BY TOTAL_STOCK_RECEIVED DESC
LIMIT 10;

-- TOP PRODUCT BY DAMAGED STOCK

SELECT P.PRODUCT_NAME, SUM(I.damaged_stock) AS TOTAL_DAMAGE_STOCK
FROM inventory I
JOIN products P
ON P.product_id = I.product_id
group by P.product_name
ORDER BY TOTAL_DAMAGE_STOCK DESC
LIMIT 10;

-- CATEGORY INVENTORY ANALYSIS

SELECT P.CATEGORY, SUM(I.STOCK_RECEIVED) AS STOCK_RECEIVED,
SUM(I.DAMAGED_STOCK) AS DAMAGED_STOCK, 
ROUND(SUM(I.DAMAGED_STOCK) * 100.0 /SUM(I.STOCK_RECEIVED), 2) AS DAMAGE_RATE
FROM inventory I
JOIN products P
ON P.product_id = I.product_id
group by P.category
ORDER BY DAMAGE_RATE DESC;

-- PRODUCT RISK RANKING

WITH PRODUCT_RISK AS (
SELECT P.product_name, SUM(I.stock_received) AS STOCK_RECEIVED,
SUM(I.damaged_stock) AS DAMAGED_STOCK,
ROUND(SUM(I.DAMAGED_STOCK) * 100.0 / SUM(I.STOCK_RECEIVED), 2) AS DAMAGE_RATE
FROM inventory I
JOIN products P
ON P.product_id = I.product_id
GROUP BY P.product_name),
RANKED_PRODUCT AS (
SELECT PRODUCT_NAME, STOCK_RECEIVED, DAMAGED_STOCK, DAMAGE_RATE,
dense_rank() OVER (ORDER BY DAMAGE_RATE DESC) AS RANKING
FROM PRODUCT_RISK)

SELECT *
FROM RANKED_PRODUCT
WHERE RANKING <= 10;