USE BLINKIT;

-- DELIVERY OVERVIEW KPIs

-- 1.TOTAL DELIVERIES
SELECT COUNT(*) AS TOTAL_DELIVERIES
FROM DELIVERY_PERFORMANCE;

-- 2.DELIVERY STATUS DISTRIBUTION
SELECT DELIVERY_STATUS, COUNT(*) AS ORDER_COUNT,
ROUND(COUNT(*) * 100.0 / (SELECT COUNT(*) FROM DELIVERY_PERFORMANCE), 2) AS PERCENTAGE
FROM DELIVERY_PERFORMANCE
GROUP BY DELIVERY_STATUS
ORDER BY PERCENTAGE DESC, ORDER_COUNT DESC;

-- 3.ON-TIME DELIVERY RATE
SELECT ROUND(SUM(CASE
WHEN UPPER(DELIVERY_STATUS) = 'ON TIME' THEN 1
ELSE 0
END) * 100.0 / COUNT(*),2) AS ON_TIME_DELIVERY_RATE
FROM DELIVERY_PERFORMANCE;

-- DELIVERY TIME ANALYSIS

-- 1.AVERAGE DELIVERY TIME
SELECT ROUND(AVG(DELIVERY_TIME_MINUTES), 2) AS AVG_DELIVERY_TIME
FROM DELIVERY_PERFORMANCE;

-- 2.FASTEST DELIVERY
WITH DELIVERY_TIME AS (
SELECT ORDER_ID, DELIVERY_TIME_MINUTES,
dense_rank() OVER (ORDER BY DELIVERY_TIME_MINUTES, ORDER_ID) AS RANKING
FROM DELIVERY_PERFORMANCE
)
SELECT *
FROM DELIVERY_TIME
WHERE RANKING <= 10;

-- 3.SLOWEST DELIVERY
WITH DELIVERY_TIME AS (
SELECT ORDER_ID, DELIVERY_TIME_MINUTES,
dense_rank() OVER (ORDER BY DELIVERY_TIME_MINUTES DESC, ORDER_ID) AS RANKING
FROM DELIVERY_PERFORMANCE
)
SELECT *
FROM DELIVERY_TIME
WHERE RANKING <= 10;

-- DELAY REASON ANALYSIS

SELECT REASONS_IF_DELAYED, COUNT(*) AS OCCURANCE,
ROUND(COUNT(*)*100.0/(SELECT COUNT(*) FROM DELIVERY_PERFORMANCE),2) AS PERCENTAGE
FROM DELIVERY_PERFORMANCE
WHERE REASONS_IF_DELAYED != ""
GROUP BY REASONS_IF_DELAYED;

-- DELIVERY PARTNER PERFORMANCE

-- 1.PARTNER ORDER VOLUME
SELECT DELIVERY_PARTNER_ID, COUNT(*) AS DELIVERIES
FROM DELIVERY_PERFORMANCE
GROUP BY DELIVERY_PARTNER_ID
ORDER BY DELIVERIES DESC
LIMIT 10;

-- DISTANCE VS DELIVERY TIME

SELECT ROUND(DISTANCE_KM,0) AS DISTANCE_BUCKET,
COUNT(*) AS ORDER_COUNTS,
ROUND(AVG(DELIVERY_TIME_MINUTES),2) AS AVG_DELIVERY_TIME
FROM DELIVERY_PERFORMANCE
GROUP BY ROUND(DISTANCE_KM,0)
ORDER BY DISTANCE_BUCKET;

-- MONTHLY DELIVERY PERFORMANCE

SELECT YEAR(O.ORDER_DATE) AS YEAR,
MONTH(O.ORDER_DATE) AS MONTH,
COUNT(*) AS TOTAL_ORDERS,
SUM(CASE
WHEN UPPER(D.DELIVERY_STATUS) = 'ON TIME' THEN 1
ELSE 0
END) AS ON_TIME_ORDER,
ROUND(SUM(CASE
WHEN UPPER(D.DELIVERY_STATUS) = 'ON TIME' THEN 1
ELSE 0
END)*100.0/COUNT(*),2) AS ON_TIME_RATE
FROM DELIVERY_PERFORMANCE D
JOIN ORDERS O
ON O.ORDER_ID = D.ORDER_ID
GROUP BY YEAR(O.ORDER_DATE), MONTH(O.ORDER_DATE)
ORDER BY YEAR, MONTH;

-- DELIVERY SLA ANALYSIS

SELECT COUNT(*) AS TOTAL_ORDER,
SUM(CASE
WHEN ACTUAL_TIME <= PROMISED_TIME THEN 1
ELSE 0
END) AS MET_SLA,
ROUND(SUM(CASE
WHEN ACTUAL_TIME <= PROMISED_TIME THEN 1
ELSE 0
END)*100.0/COUNT(*),2) AS SLA_COMPLIANCE_RATE
FROM DELIVERY_PERFORMANCE;

-- DELIVERY RISK RANKING

SELECT DELIVERY_PARTNER_ID, COUNT(*) AS TOTAL_ORDERS,
SUM(CASE
WHEN UPPER(DELIVERY_STATUS) <> 'ON TIME' THEN 1
ELSE 0
END) AS DELAYED_ORDER,
ROUND(SUM(CASE
WHEN UPPER(DELIVERY_STATUS) <> 'ON TIME' THEN 1
ELSE 0
END)*100.0/COUNT(*),2) AS DELAY_RATE
FROM DELIVERY_PERFORMANCE
GROUP BY DELIVERY_PARTNER_ID
ORDER BY DELAY_RATE DESC, DELIVERY_PARTNER_ID
LIMIT 10;