USE BLINKIT;

-- MARKET OVERVIEW KPIs

-- 1.TOTAL SPEND
SELECT ROUND(SUM(SPEND),2) AS TOTAL_SPEND
FROM MARKETING_PERFORMANCE;

-- 2.TOTAL REVENUE GENERATED
SELECT ROUND(SUM(REVENUE_GENERATED), 2) AS TOTAL_REVENUE_GENERATED
FROM MARKETING_PERFORMANCE;

-- 3.OVERALL ROAS
SELECT ROUND(SUM(REVENUE_GENERATED)/SUM(SPEND),2) AS OVERALL_ROAS
FROM MARKETING_PERFORMANCE;

-- 4.TOTAL IMPRESSIONS
SELECT SUM(IMPRESSIONS) AS TOTAL_IMPRESSIONS
FROM MARKETING_PERFORMANCE;

-- 5.TOTAL CLICKS
SELECT SUM(CLICKS) AS TOTAL_CLICKS
FROM MARKETING_PERFORMANCE;

-- 6.TOTAL CONVERSIONS
SELECT SUM(CONVERSIONS) AS TOTAL_CONVERSIONS
FROM MARKETING_PERFORMANCE;

-- MARKETING FUNNEL ANALYSIS

SELECT ROUND(SUM(CLICKS)*100.0/SUM(IMPRESSIONS), 2) AS CTR,
ROUND(SUM(CONVERSIONS)*100.0/SUM(CLICKS), 2) AS CONVERSION_RATE
FROM MARKETING_PERFORMANCE;

-- CAMPAIGN PERFORMANCE

-- 1.REVENUE
SELECT CAMPAIGN_NAME,
ROUND(SUM(REVENUE_GENERATED), 2) AS REVENUE
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY REVENUE DESC;

-- 2.SPEND
SELECT CAMPAIGN_NAME,
ROUND(SUM(SPEND), 2) AS SPEND
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY SPEND DESC;

-- 3.CONVERSION
SELECT CAMPAIGN_NAME,
ROUND(SUM(CONVERSIONS), 2) AS CONVERSIONS
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY CONVERSIONS DESC;

-- 4.ROAS
SELECT CAMPAIGN_NAME,
ROUND(SUM(REVENUE_GENERATED)/SUM(SPEND),2) AS ROAS
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY ROAS DESC;

-- CHANNEL PERFORMANCE

SELECT CHANNEL,
ROUND(SUM(IMPRESSIONS),2) AS IMPRESSIONS,
ROUND(SUM(CLICKS), 2) AS CLICKS,
ROUND(SUM(CONVERSIONS), 2) AS CONVERSIONS,
ROUND(SUM(SPEND), 2) AS SPEND,
ROUND(SUM(REVENUE_GENERATED)) AS REVENUE,
ROUND(SUM(REVENUE_GENERATED)/SUM(SPEND), 2) AS ROAS
FROM MARKETING_PERFORMANCE
GROUP BY CHANNEL
ORDER BY ROAS DESC;

-- MONTHLY MARKETING PERFORMANCE

SELECT YEAR(DATE) AS YEAR, MONTH(DATE) AS MONTH,
ROUND(SUM(SPEND), 2) AS SPEND,
ROUND(SUM(REVENUE_GENERATED)) AS REVENUE,
ROUND(SUM(REVENUE_GENERATED)/SUM(SPEND), 2) AS ROAS
FROM MARKETING_PERFORMANCE
GROUP BY YEAR(DATE), MONTH(DATE)
ORDER BY YEAR, MONTH;

-- COST PER CLICK (CPC)

SELECT CAMPAIGN_NAME,
ROUND(SUM(SPEND)/SUM(CLICKS), 2) AS CPC
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY CPC;

-- COST PPER ACQUISITION (CPA)

SELECT CAMPAIGN_NAME,
ROUND(SUM(SPEND)/SUM(CONVERSIONS),2) AS CPA
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
ORDER BY CPA;

-- CAMPAIGN RANKING

WITH CAMPAIGN_RANKING AS (
SELECT CAMPAIGN_NAME, ROUND(SUM(REVENUE_GENERATED),2) AS REVENUE,
ROUND(SUM(REVENUE_GENERATED)/SUM(SPEND),2) AS ROAS
FROM MARKETING_PERFORMANCE
GROUP BY CAMPAIGN_NAME
)
SELECT *, dense_rank() OVER (ORDER BY ROAS DESC, REVENUE DESC) REVENUE_RANKING
FROM CAMPAIGN_RANKING;