USE BLINKIT;

-- EXECUTIVE KPI DASBOARD

SELECT
(SELECT COUNT(*) FROM CUSTOMERS) AS TOTAL_CUSTOMERS,
(SELECT COUNT(*) FROM ORDERS) AS TOTAL_ORDERS,
ROUND((SELECT SUM(ORDER_TOTAL) FROM ORDERS),2) AS TOTAL_REVENUE,
ROUND((SELECT AVG(ORDER_TOTAL) FROM ORDERS),2) AS AVG_ORDER_VALUE,
ROUND((SELECT COUNT(*) FROM (
SELECT CUSTOMER_ID
FROM ORDERS
GROUP BY CUSTOMER_ID
HAVING COUNT(*) > 1) T)*100.0/(SELECT COUNT(DISTINCT CUSTOMER_ID) FROM ORDERS),2) AS REPEAT_CUSTOMER_RATE,
ROUND((SELECT (SELECT COUNT(*) FROM ORDERS WHERE UPPER(DELIVERY_STATUS) = 'ON TIME')*100.0/ COUNT(*) FROM ORDERS),2) AS ON_TIME_DELIVERY_RATE,
ROUND((SELECT SUM(DAMAGED_STOCK)*100.0/SUM(STOCK_RECEIVED) FROM INVENTORY),2) AS INVENTORY_DAMAGE_RATE,
ROUND((SELECT SUM(REVENUE_GENERATED)/SUM(SPEND) FROM MARKETING_PERFORMANCE),2) AS MARKETING_ROAS;

-- REPEAT CUSTOMER KPI

SELECT
COUNT(*) AS TOTAL_CUSTOMERS,

SUM(CASE
WHEN ORDER_COUNT > 1 THEN 1
ELSE 0
END) AS REPEAT_CUSTOMERS,

ROUND(
SUM(CASE
WHEN ORDER_COUNT > 1 THEN 1
ELSE 0
END) * 100.0 /
COUNT(*)
,2) AS REPEAT_CUSTOMER_RATE

FROM (
    SELECT CUSTOMER_ID,
           COUNT(*) AS ORDER_COUNT
    FROM ORDERS
    GROUP BY CUSTOMER_ID
) T;

-- CUSTOMER SEGMENT REVENUE CONTRIBUTION

SELECT C.CUSTOMER_SEGMENT,
COUNT(DISTINCT C.CUSTOMER_ID) AS CUSTOMERS,
ROUND(SUM(O.ORDER_TOTAL),2) AS REVENUE,
ROUND(SUM(O.ORDER_TOTAL)*100.0/
(SELECT SUM(ORDER_TOTAL) FROM ORDERS), 2) AS REVENUE_SHARE
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMER_ID = C.CUSTOMER_ID
GROUP BY C.CUSTOMER_SEGMENT
ORDER BY REVENUE DESC;

-- REVENUE BY DELIVERY STATUS

SELECT D.DELIVERY_STATUS,
COUNT(*) AS TOTAL_ORDERS,
ROUND(SUM(O.ORDER_TOTAL),2) AS REVENUE,
ROUND(AVG(O.ORDER_TOTAL),2) AS AVG_ORDER_VALUE,
ROUND(SUM(O.ORDER_TOTAL)*100.0/(SELECT SUM(ORDER_TOTAL) FROM ORDERS),2) AS REVENUE_SHARE
FROM ORDERS O
JOIN DELIVERY_PERFORMANCE D
ON D.ORDER_ID = O.ORDER_ID
GROUP BY D.DELIVERY_STATUS
ORDER BY REVENUE DESC;

-- CUSTOMER SEGMENT vs DELIVERY EXPERIENCE

SELECT C.CUSTOMER_SEGMENT,
COUNT(*) AS TOTAL_ORDERS,
SUM(CASE WHEN UPPER(D.DELIVERY_STATUS) <> 'ON TIME' THEN 1
ELSE 0
END) AS DELAYED_ORDERS,
ROUND(SUM(CASE WHEN UPPER(D.DELIVERY_STATUS) <> 'ON TIME' THEN 1
ELSE 0
END)*100/COUNT(*),2) AS DELAY_RATE
FROM CUSTOMERS C
JOIN ORDERS O
ON O.CUSTOMER_ID = C.CUSTOMER_ID
JOIN DELIVERY_PERFORMANCE D
ON D.ORDER_ID = O.ORDER_ID
GROUP BY C.CUSTOMER_SEGMENT
ORDER BY DELAY_RATE DESC;

-- CATEGORY REVENUE vs INVENTORY DAMAGE

WITH CATEGORY_REVENUE AS (

SELECT
    P.CATEGORY,
    ROUND(SUM(O.ORDER_TOTAL),2) AS REVENUE
FROM ORDERS O
JOIN ORDER_ITEMS OI
    ON O.ORDER_ID = OI.ORDER_ID
JOIN PRODUCTS P
    ON P.PRODUCT_ID = OI.PRODUCT_ID
GROUP BY P.CATEGORY
),

CATEGORY_DAMAGE AS (

SELECT
    P.CATEGORY,
    SUM(I.STOCK_RECEIVED) AS STOCK_RECEIVED,
    SUM(I.DAMAGED_STOCK) AS DAMAGED_STOCK,
    ROUND(
        SUM(I.DAMAGED_STOCK)*100.0/
        SUM(I.STOCK_RECEIVED)
    ,2) AS DAMAGE_RATE
FROM INVENTORY I
JOIN PRODUCTS P
    ON P.PRODUCT_ID = I.PRODUCT_ID
GROUP BY P.CATEGORY
)

SELECT
    R.CATEGORY,
    R.REVENUE,
    D.DAMAGED_STOCK,
    D.DAMAGE_RATE
FROM CATEGORY_REVENUE R
JOIN CATEGORY_DAMAGE D
    ON R.CATEGORY = D.CATEGORY
ORDER BY R.REVENUE DESC;

-- High Revenue Products with High Damage

WITH PRODUCT_REVENUE AS (
SELECT P.PRODUCT_ID, P.PRODUCT_NAME,
ROUND(SUM(OI.UNIT_PRICE * OI.QUANTITY),2) AS REVENUE
FROM PRODUCTS P
JOIN ORDER_ITEMS OI
ON OI.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID, P.PRODUCT_NAME
), PRODUCT_DAMAGE AS (
SELECT I.PRODUCT_ID, SUM(I.DAMAGED_STOCK) AS DAMAGED_STOCK
FROM INVENTORY I
GROUP BY I.PRODUCT_ID
)
SELECT PR.PRODUCT_NAME, PR.REVENUE, PD.DAMAGED_STOCK 
FROM PRODUCT_REVENUE PR
JOIN PRODUCT_DAMAGE PD
ON PD.PRODUCT_ID = PR.PRODUCT_ID
ORDER BY REVENUE DESC, DAMAGED_STOCK DESC
LIMIT 10;

-- MARKETING vs ACTUAL SALES

SELECT 
ROUND((SELECT SUM(REVENUE_GENERATED) FROM MARKETING_PERFORMANCE),2) AS MARKETING_REVENUE,
ROUND((SELECT SUM(ORDER_TOTAL) FROM ORDERS),2) AS ACTUAL_ORDER_REVENUE,
ROUND((SELECT SUM(REVENUE_GENERATED) FROM MARKETING_PERFORMANCE)/
(SELECT SUM(ORDER_TOTAL) FROM ORDERS),2) AS REVENUE_MULTIPLIER;